---
- name: Backup Unity-IdM database
  hosts: db
  tasks:  
  - set_fact:
      now: "{{ lookup('pipe', 'date +%F_%T') }}"
  - set_fact:
      targetBackupTarFile: "/tmp/unitydb-v{{ currentUnityVer }}-{{ now }}.sql.tar"
  - set_fact:
      targetBackupFile: "{{ targetBackupTarFile }}.gz"

  - name: Performing database backup on db host
    postgresql_db:
      state: dump
      login_host: "{{ backup.db.host }}"
      port: "{{ backup.db.port }}"
      login_user: "{{ backup.db.username }}"
      login_password: "{{ backup.db.password }}"
      name: "{{ backup.db.dbName }}"
      target: "{{ targetBackupTarFile }}"

  - name: "Compressing databse dump"
    shell: gzip "{{ targetBackupTarFile }}"

  - name: Store database backup on management host
    fetch:
      src: "{{ targetBackupFile }}"
      dest: "{{ backup.dbDumps }}/"
      flat: yes

  - name: Delete backup file on db host
    file:
      state: absent
      path: "{{ targetBackupFile }}"
