---
- name: Restore Unity-IdM database
  hosts: unity
  vars:
    targetSQLFile: "{{ backupFilePath | replace('.gz','') }}"
  tasks:
  - name: Deompress backup file
    command: gunzip {{backupFilePath}}

  - name: Restore {{ backup.db.dbName }} database
    shell: mysql -u {{backup.db.username}} -p"{{backup.db.password}}" -h {{backup.db.host}} --port {{backup.db.port}} {{ backup.db.dbName }} < {{targetSQLFile}}

  - name: Compress SQL backup file
    command: gzip {{targetSQLFile}}

