---
- name: Setup styles
  gather_facts: no
  vars:
    currentBin: "{{installationDir}}/bin/"
  hosts: unity
  tasks:

  - name: Find all styles.scss files
    find:
      paths: "{{installationDir}}/webContents"
      recurse: yes
      patterns: "styles.scss"
      file_type: file
    register: stylesFiles

  - name: Compile scss
    shell: "{{ currentBin }}/unity-idm-scss-compile {{ item.path | replace('styles.scss', '')}}"
    args:
      chdir: "{{ currentBin }}"
    with_items: "{{ stylesFiles.files }}"
    