installDir: "{{inventory_dir}}/service"
unityVersion: 3.13.1

unity:
  connectivityCheckHost: localhost:2443
  confDir: "{{inventory_dir}}/files/conf"
  webContentsDir: "{{inventory_dir}}/files/webContents"
  extraDirs: 
    - "{{inventory_dir}}/files/lib-extra"

backup:
  dbDumps: "{{inventory_dir}}/db_dumps"
  db:
    backupMethod: mysql-native-cmds # or ansible-native-mysql, ansible-native-postgresql
    host: localhost
    port: 3306
    dbName: unity-database-name
    username: username
    password: password
